# This file is part of the CodeDiff code diffing tool.
#
# Copyright (C) 2026 Marko Ivankovic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# The Homebrew formula for the tap at github.com/ivankovic/homebrew-codediff, as a template:
# scripts/render_homebrew_formula.py fills the version and the checksums from a release's
# SHA256SUMS.txt, and release.yml pushes the result to the tap. The installed binary is the same
# attested release asset every other route ships, so `brew install` takes seconds instead of the
# ten-minute grammar-and-LTO compile a build-from-source formula would run on every machine.
class Codediff < Formula
  desc "Fast, robust, syntax-aware code diffing"
  homepage "https://github.com/ivankovic/codediff"
  version "0.1.1"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.1/codediff-aarch64-apple-darwin.tar.gz"
      sha256 "1fcfb87886e443d220e7b098b255f1491db029ba16f550c975f5beb4f54adb5c"
    end
    on_intel do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.1/codediff-x86_64-apple-darwin.tar.gz"
      sha256 "c51093a4744de23c9ad13777634c8b605cfde2d36e69a59f419e55e7c1a8b90c"
    end
  end

  # The static musl binaries: Homebrew on Linux runs on any distribution, and these run on any
  # glibc, or none.
  on_linux do
    on_arm do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.1/codediff-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e2b62d2694bb6990e868f0efb736f5a5b73d313ad62c2b49f7dbf0e8f26c6b80"
    end
    on_intel do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.1/codediff-x86_64-unknown-linux-musl.tar.gz"
      sha256 "efeb29c940b4defc93dc8ffe9906a08e787f9e86452e6d32d5c3aa57d30a24ff"
    end
  end

  def install
    bin.install "codediff"
    # Generated by the binary just installed, from the same clap definition as --help.
    (man1/"codediff.1").write Utils.safe_popen_read(bin/"codediff", "util", "man")
    generate_completions_from_executable(bin/"codediff", "util", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/codediff --version")
    (testpath/"before.py").write "def f(x):\n    return x + 1\n"
    (testpath/"after.py").write "def f(x):\n    return x + 2\n"
    output = shell_output("#{bin}/codediff --headless before.py after.py")
    assert_match "x + 2", output
  end
end
