# This file is part of the CodeDiff code diffing tool.
#
# Copyright (C) 2026 Marko Ivankovic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# The Homebrew formula for the tap at github.com/ivankovic/homebrew-codediff, as a template:
# scripts/render_homebrew_formula.py fills the version and the checksums from a release's
# SHA256SUMS.txt, and release.yml pushes the result to the tap. The installed binary is the same
# attested release asset every other route ships, so `brew install` takes seconds instead of the
# ten-minute grammar-and-LTO compile a build-from-source formula would run on every machine.
class Codediff < Formula
  desc "Fast, robust, syntax-aware code diffing"
  homepage "https://github.com/ivankovic/codediff"
  version "0.1.0"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.0/codediff-aarch64-apple-darwin.tar.gz"
      sha256 "6d63b23f7e63875fa1f551c8b392edc0150e37e25c0fa6b0d051afde39eb3560"
    end
    on_intel do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.0/codediff-x86_64-apple-darwin.tar.gz"
      sha256 "04d30e893f33d1018f0a42dde9e0fc7a0cecd9ca456e9e58906a4a9e55721b42"
    end
  end

  # The static musl binaries: Homebrew on Linux runs on any distribution, and these run on any
  # glibc, or none.
  on_linux do
    on_arm do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.0/codediff-aarch64-unknown-linux-musl.tar.gz"
      sha256 "681542877b8a613fb0eaa4258af8c2f4a92884f779baa5ddaf40941d2567fd30"
    end
    on_intel do
      url "https://github.com/ivankovic/codediff/releases/download/v0.1.0/codediff-x86_64-unknown-linux-musl.tar.gz"
      sha256 "af0aebba78a939ac66e8b546fead762ee01b7de1645639dfcbbfb5ad4e905afd"
    end
  end

  def install
    bin.install "codediff"
    # Generated by the binary just installed, from the same clap definition as --help.
    (man1/"codediff.1").write Utils.safe_popen_read(bin/"codediff", "util", "man")
    generate_completions_from_executable(bin/"codediff", "util", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/codediff --version")
    (testpath/"before.py").write "def f(x):\n    return x + 1\n"
    (testpath/"after.py").write "def f(x):\n    return x + 2\n"
    output = shell_output("#{bin}/codediff --headless before.py after.py")
    assert_match "x + 2", output
  end
end
