# This file is part of the OmniDiff code diffing tool.
#
# Copyright (C) 2026 Marko Ivankovic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# The Homebrew formula for the tap at github.com/ivankovic/homebrew-omnidiff, as a template:
# scripts/render_homebrew_formula.py fills the version and the checksums from a release's
# SHA256SUMS.txt, and release.yml pushes the result to the tap. The installed binary is the same
# attested release asset every other route ships, so `brew install` takes seconds instead of the
# ten-minute grammar-and-LTO compile a build-from-source formula would run on every machine.
class Omnidiff < Formula
  desc "Fast, robust, syntax-aware code diffing"
  homepage "https://github.com/ivankovic/omnidiff"
  version "0.2.0"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/ivankovic/omnidiff/releases/download/v0.2.0/omnidiff-aarch64-apple-darwin.tar.gz"
      sha256 "297bf83a6293ec570c7c0349291368b67861d8bbe82de79b986bdea4da7d78a1"
    end
    on_intel do
      url "https://github.com/ivankovic/omnidiff/releases/download/v0.2.0/omnidiff-x86_64-apple-darwin.tar.gz"
      sha256 "eaf8cbc6b2e6d15c8c257bc429da9c4be8c13374420df152fd5940a99d90df28"
    end
  end

  # The static musl binaries: Homebrew on Linux runs on any distribution, and these run on any
  # glibc, or none.
  on_linux do
    on_arm do
      url "https://github.com/ivankovic/omnidiff/releases/download/v0.2.0/omnidiff-aarch64-unknown-linux-musl.tar.gz"
      sha256 "320815727140e6e3bcfab89e71952fed4ae1239fb1a2fe8bfafa484e485ec7ff"
    end
    on_intel do
      url "https://github.com/ivankovic/omnidiff/releases/download/v0.2.0/omnidiff-x86_64-unknown-linux-musl.tar.gz"
      sha256 "0d8dd41676963a376100b3149c3210e1c0f4f52f7a15d44bd6e90e463e8d2c1b"
    end
  end

  def install
    bin.install "omnidiff"
    # Generated by the binary just installed, from the same clap definition as --help.
    (man1/"omnidiff.1").write Utils.safe_popen_read(bin/"omnidiff", "util", "man")
    generate_completions_from_executable(bin/"omnidiff", "util", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omnidiff --version")
    (testpath/"before.py").write "def f(x):\n    return x + 1\n"
    (testpath/"after.py").write "def f(x):\n    return x + 2\n"
    output = shell_output("#{bin}/omnidiff --headless before.py after.py")
    assert_match "x + 2", output
  end
end
